### PR TITLE
We throw an exception if you tap the screen during load

### LINKED ISSUE #1960: exception if you tap screen during load
It's possible to attempt a hitTest before we've attempted the first layout. If you do this, then you get an exception because the hitTest logic is only valid once you've done layout.

### PR DESCRIPTION
**Pull request by abarth**
Inside runApp, we were building the render tree for the app, but we weren't
calling layout, which meant we were running a hit test on a dirty tree. Now
hitTest specifically asserts that the tree is clean and we synchronously call
layout for your app during runApp.

Fixes #1960

### CODE REVIEW

File: sky/packages/sky/lib/src/rendering/binding.dart [hunk 1]
```diff
@@ -172,8 +172,12 @@ class FlutterBinding extends HitTestTarget {
       listener(size);
   }
 
+  void _handlePersistentFrameCallback(Duration timeStamp) {
+    beginFrame();
+  }
+
   /// Pump the rendering pipeline to generate a frame for the given time stamp
-  void beginFrame(Duration timeStamp) {
+  void beginFrame() {
```
Comment (Hixie) [inline sky/packages/sky/lib/src/rendering/binding.dart]: LGTM, but come to think of it, how do we ensure that the animation persistent frame callbacks are called before this one?

Comment (abarth) [inline sky/packages/sky/lib/src/rendering/binding.dart]: Those are transient callbacks, which always run first.

Comment (Hixie) [inline sky/packages/sky/lib/src/rendering/binding.dart]: Ah, excellent. It's like someone designed it or something.
