### PR TITLE
Handle mouseover events in pointer event conversion

### LINKED ISSUE #1806: method not found: 'pointer' on mouseover event
MouseOver events generate the following stackdump running the `examples/widgets/scale.dart` sample code under Mojo shell under Linux:

```
[1026/150556:ERROR:dart_error.cc(16)] Unhandled exception:
The null object does not have a getter 'pointer'.

NoSuchMethodError: method not found: 'pointer'
Receiver: null
Arguments: []
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:42)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:45)
#2      _UiEventConverter.convertPointerEvent (packages/flutter/src/rendering/binding.dart:98)
#3      _UiEventConverter.convert (packages/flutter/src/rendering/binding.dart:47)
#4      FlutterBinding._handleEvent (packages/flutter/src/rendering/binding.dart:181)
```

To repro, run examples/widgets/scale.dart like this and move the mouse around the window:
`pub run sky_tools build --main=scale.dart && pub run sky_tools run_mojo --mojo-path ~/mojo/src`

(requires a Mojo build to be present in ~/mojo/src.)

This problem happens on all of the samples I've tried.

### PR DESCRIPTION
**Pull request by krisgiesing**
Fixes #1806

### CODE REVIEW

File: sky/packages/sky/lib/src/rendering/binding.dart [hunk 1]
```diff
@@ -92,10 +92,12 @@ class _UiEventConverter {
         break;
     }
 
+    int pointer = (state == null) ? event.pointer : state.pointer;
```
Comment (abarth) [inline sky/packages/sky/lib/src/rendering/binding.dart]: No need for ( )

**Comment by abarth** [comment]
LGTM

File: sky/packages/sky/lib/src/rendering/binding.dart (hunk 1 above)
Comment (krisgiesing) [inline sky/packages/sky/lib/src/rendering/binding.dart]: Personally I find it easier to read with ( ) because of the visual confusion that x = y == z ... might cause, but I'm happy to use local style if it's preferred without

Comment (abarth) [inline sky/packages/sky/lib/src/rendering/binding.dart]: Ok.  I suspect we're already not using a consistent style on this point.  :)

Comment (Hixie) [inline sky/packages/sky/lib/src/rendering/binding.dart]: Aren't you mixing two namespaces here? (The OS pointer IDs and the Flutter pointer IDs?)

I think we shouldn't be even receiving hover events unless we also implement pointeradd/pointerremove.
