### PR TITLE
Convert Drawer to using navigator

### LINKED ISSUE #715: Drawer.initState() fails
Launch the stocks demo and then immediately tap the "show drawer" icon (toolbar left).
```
E/chromium(16844): [ERROR:dart_error.cc(19)] Unhandled exception:
E/chromium(16844): 'http://localhost:9888/packages/sky/widgets/framework.dart': Failed assertion: line 691 pos 12: '!_isBuilding' is not true.
E/chromium(16844): #0      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:27)
E/chromium(16844): #1      Component._scheduleBuild (http://localhost:9888/packages/sky/widgets/framework.dart:691:12)
E/chromium(16844): #2      StatefulComponent.setState (http://localhost:9888/packages/sky/widgets/framework.dart:775:5)
E/chromium(16844): #3      Navigator.push (http://localhost:9888/packages/sky/widgets/navigator.dart:179:5)
E/chromium(16844): #4      Navigator.pushState (http://localhost:9888/packages/sky/widgets/navigator.dart:169:5)
E/chromium(16844): #5      Drawer.initState (http://localhost:9888/packages/sky/widgets/drawer.dart:71:17)
E/chromium(16844): #6      StatefulComponent._sync (http://localhost:9888/packages/sky/widgets/framework.dart:746:7)
E/chromium(16844): #7      Widget.syncChild (http://localhost:9888/packages/sky/widgets/framework.dart:359:13)
E/chromium(16844): #8      Scaffold.syncRenderObject (http://localhost:9888/packages/sky/widgets/scaffold.dart:231:22)
E/chromium(16844): #9      RenderObjectWrapper._sync (http://localhost:9888/packages/sky/widgets/framework.dart:923:5)
```
This occurs because Drawer.initState() is called while the Navigator is building and Drawer.initState() implicitly does Navigator.scheduleBuild():
```
    if (navigator != null) {
      navigator.pushState(this, (_) => _performance.reverse()); // ... navigator.scheduleBuild()
    }
```
This statement enables the back button to DTRT.

It's happening at initState() time because the Drawer is being created with its open animation started. Drawer appears to mostly ignore its showing property. For example creating a Drawer with showing:false doesn't appear to work. The stocks demo cooperates by only creating the Drawer when it's time to show it.

The bug can be worked around by restoring the '\\\ooooo/////' workaround removed by https://github.com/domokit/sky_engine/pull/592.

### PR DESCRIPTION
**Pull request by abarth**
This patch converts drawer to using the "openDialog" pattern for managing its
state. Currently, the drawer entrance and exit animation aren't integrated with
the navigator's animation system because the drawer's animations can be stopped
and reversed, which the navigator can't yet understand. That means dismissing
the drawer via the system back button causes the drawer to be removed
instanteously.

Fixes #715

### CODE REVIEW

**Comment by abarth** [comment]
@Hixie @HansMuller

File: sky/packages/sky/lib/src/animation/animation_performance.dart [hunk 1]
```diff
@@ -79,9 +79,6 @@ class AnimationPerformance implements WatchableAnimationPerformance {
   /// If non-null, animate with this timing instead of a linear timing
   AnimationTiming timing;
 
-  /// If non-null, animate with this force instead of a zero-to-one timeline.
-  Force attachedForce;
```
Comment (abarth) [inline sky/packages/sky/lib/src/animation/animation_performance.dart]: This feature doesn't have any clients anymore.

**Comment by abarth** [comment]
Fixed #1187

File: examples/fitness/lib/feed.dart [hunk 2]
```diff
@@ -66,19 +66,14 @@ class FeedFragmentState extends State<FeedFragment> {
...
-      return null;
-    return new Drawer(
-      showing: _drawerShowing,
-      level: 3,
-      onDismissed: _handleDrawerDismissed,
+  void _showDrawer() {
+    showDrawer(
       navigator: config.navigator,
-      children: [
+      child: new Block([
```
Comment (Hixie) [inline examples/fitness/lib/feed.dart]: In some apps, the header doesn't scroll, only the items scroll. What does Material say?

File: examples/fitness/lib/feed.dart [hunk 3]
```diff
@@ -262,8 +241,7 @@ class FeedFragmentState extends State<FeedFragment> {
       toolbar: buildToolBar(),
       body: buildBody(),
       snackBar: buildSnackBar(),
-      floatingActionButton: buildFloatingActionButton(),
-      drawer: buildDrawer()
+      floatingActionButton: buildFloatingActionButton()
```
Comment (Hixie) [inline examples/fitness/lib/feed.dart]: The real reason for this PR is hiding right here. ;-)

File: examples/widgets/card_collection.dart [hunk 4]
```diff
@@ -114,17 +115,11 @@ class CardCollectionAppState extends State<CardCollectionApp> {
...
-  }
-
-  void _handleDrawerDismissed() {
-    setState(() {
-      _drawerStatus = AnimationStatus.dismissed;
-    });
+  void _showDrawer() {
+    showDrawer(
+      navigator: config.navigator,
+      child: _buildDrawerContent()
```
Comment (Hixie) [inline examples/widgets/card_collection.dart]: inline _buildDrawerContent unless it's actually used in two places.

**Comment by Hixie** [comment]
LGTM.

What do you need from Navigator to have it support pointer-driven inputs to the route animation?

File: examples/fitness/lib/feed.dart (hunk 2 above)
Comment (abarth) [inline examples/fitness/lib/feed.dart]: I believe its all supposed to scroll in material.

**Comment by Hixie** [comment]
This broke stateful drawers, like card_collection (and probably stocks). Their checkboxes no longer update in the rendering when you tap them.
