### PR TITLE
KeyboardServiceState#setSelection shouldn't crash

### LINKED ISSUE #1033: Considering a different way to retrieve parentData
Right now, in RenderObject, we see this line:

```
dynamic parentData; // TODO(ianh): change the type of this back to ParentData once the analyzer is cleverer
```

and uses like this:

```
// inside some parent
assert(child.parentData is SpecificThing);
SpecificThing localParentData = child.parentData;
localParentData.callMethodOnlyOnSpecificThing(); // no warning
```

My understanding is that a parent is able to set a specific type of parentData on a child, and the parent should expect to get that parentData back from the child. The parent wants to treat the returned parentData as a specific type.

One idea is to invert who is responsible for returning the parentData. What if we asked the parent for that?

```
// inside some parent
this.parentDataFrom(child).callMethodOnlyOnSpecificThing(); // no warning!
```

Note: RenderObject's parentData might still be dynamic. However, for each subclass of RenderObject, there is a method that returns a specific type of parentData. Something like:

```
class SpecificParent extends RenderObject {
  SpecificParentData parentDataFrom(child) => child.parentData;
}

class OtherSpecificParent extends RenderObject {
  OtherSpecificParentData parentDataFrom(child) => child.parentData;
}
```

Of course, RenderObject would have an abstract method called parentDataFrom() that returns dynamic. The contract would be that subclasses would implement that method and use a more specific return type. That's OK by Dart!

### PR DESCRIPTION
**Pull request by abarth**
Now we sanity check our inputs instead of crashing.

Fixes https://github.com/flutter/flutter/issues/1033

### CODE REVIEW

**Comment by abarth** [comment]
@Hixie

File: services/keyboard/src/org/chromium/mojo/keyboard/KeyboardServiceState.java [hunk 1]
```diff
@@ -59,6 +59,9 @@ public void setText(String text) {
     }
 
     public void setSelection(int start, int end) {
+        int length = mActiveEditable.length();
+        start = Math.min(start, length);
+        end = Math.min(start, length);
         Selection.setSelection(mActiveEditable, start, end);
```
Comment (Hixie) [inline services/keyboard/src/org/chromium/mojo/keyboard/KeyboardServiceState.java]: max end length

**Comment by Hixie** [comment]
lgtm
